[build]
command = "hugo --minify"
publish = "public"

[build.environment]
HUGO_VERSION = "0.147.7"

[build.processing.html]
pretty_urls = false

[[redirects]]
from = "/index.xml"
to = "/posts/index.xml"
status = 301
force = true
